swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /dataset:
    get:
      operationId: "dataset.read"
      tags:
        - "Dataset"
      summary: "The dataset available on the analytics server"
      description: "Read the list of dataset"
      responses:
        200:
          description: "Successful read dataset list operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                lastModified:
                  type: "string"
                filesize:
                  type: "string"